project_id = "rydwxrfbsoosmcpqaqid"

[functions.get-mapbox-token]
verify_jwt = false

[functions.create-provider-checkout]
verify_jwt = false

[functions.verify-provider-payment]
verify_jwt = false

[functions.increment-provider-rides]
verify_jwt = false

[functions.get-provider-subscription]
verify_jwt = false

[functions.admin-providers]
verify_jwt = false

[functions.generate-provider-slugs]
verify_jwt = false

[functions.prestadores-online]
verify_jwt = false

[functions.atualizar-localizacao-prestador]
verify_jwt = false
